import requests

# 国内IPv4 CIDR列表源（你可以换成其他可靠源）
IPV4_URL = "https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt"
# 国内IPv6 CIDR列表源（可选）
IPV6_URL = "https://raw.githubusercontent.com/gaoyifan/china-operator-ip/master/ipv6.txt"

def fetch_cidrs(url):
    try:
        resp = requests.get(url, timeout=10)
        resp.raise_for_status()
        # 按行分割并过滤空行
        return [line.strip() for line in resp.text.splitlines() if line.strip()]
    except Exception as e:
        print(f"获取 {url} 失败: {e}")
        return []

def save_ikuai_format(filename, cidrs):
    with open(filename, "w", encoding="utf-8") as f:
        # 爱快导入格式每行一个 CIDR
        for cidr in cidrs:
            f.write(cidr + "\n")
    print(f"已保存 {len(cidrs)} 条记录到 {filename}")

if __name__ == "__main__":
    ipv4_list = fetch_cidrs(IPV4_URL)
    ipv6_list = fetch_cidrs(IPV6_URL)

    if ipv4_list:
        save_ikuai_format("ikuai_cn_ipv4group.txt", ipv4_list)
    if ipv6_list:
        save_ikuai_format("ikuai_cn_ipv6group.txt", ipv6_list)
