name: 更新国内IP分组

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点执行（北京时间 8 点）
  workflow_dispatch:  # 允许手动触发

jobs:
  update-ipgroups:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码仓库
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # 指定Python版本

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests  # 脚本依赖requests库

      - name: 运行生成脚本
        run: |
          python ikuai_ipgroups.py  # 执行脚本生成IP分组文件

      - name: 检查文件变化
        id: check_changes
        run: |
          git status --porcelain
          echo "changes=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

      - name: 提交更新
        if: steps.check_changes.outputs.changes > 0
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ikuai_cn_ipv4group.txt ikuai_cn_ipv6group.txt
          git commit -m "自动更新IP分组 $(date +'%Y-%m-%d')"
          git push
