name: 每日更新爱快国内IP分组

on:
  schedule:
    - cron: '0 12 * * *'  # 每天北京时间20:00执行
  workflow_dispatch:

jobs:
  update-ipgroup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: |
          python -m pip install --upgrade pip
          pip install requests

      - run: |
          echo "=== 开始生成 IPv4 和 IPv6 分组文件 ==="
          python .github/scripts/generate_ikuai_ipgroups.py
          
          if [ ! -f "ikuai_cn_ipv4group.txt" ] || [ ! -f "ikuai_cn_ipv6group.txt" ]; then
            echo "ERROR: 未生成目标IP分组文件！"
            exit 1
          fi

      - name: 提交并推送文件到GitHub
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # 保存当前修改
          git stash
          
          # 拉取远程更新
          git pull origin main --rebase
          
          # 恢复修改
          git stash pop || true
          
          git add ./ikuai_cn_ipv4group.txt ./ikuai_cn_ipv6group.txt
          
          if git diff --cached --quiet; then
            echo "=== 无新文件或修改，无需提交 ==="
          else
            git commit -m "每日自动更新国内IP分组文件（生成时间：${{ github.run_started_at }}）"
            git push origin main
            echo "=== 文件提交并推送成功 ==="
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
