name: 每日更新爱快国内IP分组

on:
  schedule:
    - cron: '0 12 * * *'  # 每天北京时间02:00执行
  workflow_dispatch:

jobs:
  update-ipgroup:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 配置Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 安装依赖库
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 执行脚本生成IP分组文件
        run: |
          echo "=== 开始运行脚本生成文件 ==="
          python "ikuai_ipgroups.py"
          
          # 检查文件是否生成成功
          if [ ! -f "ikuai_cn_ipv4group.txt" ] || [ ! -f "ikuai_cn_ipv6group.txt" ]; then
            echo "ERROR: 未生成目标IP分组文件！"
            ls -l
            exit 1
          fi
          
          echo "=== 生成的文件如下 ==="
          ls -l ikuai_cn_ipv4group.txt ikuai_cn_ipv6group.txt

      - name: 提交并推送文件到GitHub
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          git pull origin main --rebase
          
          # 添加生成的IP分组文件
          git add ./ikuai_cn_ipv4group.txt ./ikuai_cn_ipv6group.txt
          
          echo "=== 暂存区状态 ==="
          git status
          
          if git diff --cached --quiet; then
            echo "=== 无新文件或修改，无需提交 ==="
          else
            git commit -m "每日自动更新国内IP分组文件（生成时间：${{ github.run_started_at }}）"
            git push origin main
            echo "=== 文件提交并推送成功 ==="
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 清理旧工作流记录（保留最近5条）
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 5
          workflow_id: "每日更新爱快国内IP分组"
